[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
lib_deps =
    fastled/FastLED@^3.6.0
    adafruit/Adafruit NeoPixel@^1.12.0
    adafruit/Adafruit PWM Servo Driver Library@^2.4.1
    ottowinter/ESPAsyncWebServer-esphome@^3.1.0
    mathieucarbou/AsyncTCP@^3.1.4
monitor_speed = 115200
